name: Upload single file
on: push
jobs:
  upload_file:
    name: Upload File
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World" > file.txt
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: file
          path: '*.txt'